- name: varibales from PLAY level
  hosts: localhost
  vars:
    Course: "DevOps"
    Trainer: "Shivakumar"
    Duration: "110HRS"
  tasks:
  - name: check variable
    ansible.builtin.debug:
      msg: "Hi, I'm learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"