- name: varibales from PLAY level
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: check variable
    ansible.builtin.debug:
      msg: "Hi, I'm learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"