- name: checking data types
  hosts: localhost
  vars:
    NAME: Suresh #key value 
    Skills: #skills is a list type
    - DevOps
    - Shell
    - AWS
    - Docker
    - Ansible
    - Linux
    Experience: #Experience is a map type, it contines key values pairs
      Devops: 7 
      AWS: 6
      Docker: 4
    Trainer: true #boolean
  tasks:
  - name: print key value pair
    ansible.builtin.debug:
      msg: "name: {{NAME}}"

  - name: print list
    ansible.builtin.debug:
      msg: "Skills: {{Skills}}"

  - name: print map
    ansible.builtin.debug:
      msg: "Experience: {{Experience}}"

  - name: print boolean
    ansible.builtin.debug:
      msg: "is he trainer: {{Trainer}}"